import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const projectRoot = resolve(import.meta.dirname, '..')
const pageSource = readFileSync(resolve(projectRoot, 'app/page.tsx'), 'utf8')
const globalStyles = readFileSync(resolve(projectRoot, 'app/globals.css'), 'utf8')
const layoutSource = readFileSync(resolve(projectRoot, 'app/layout.tsx'), 'utf8')
const readmeSource = readFileSync(resolve(projectRoot, 'README.md'), 'utf8')
const robotsPath = resolve(projectRoot, 'app/robots.ts')
const sitemapPath = resolve(projectRoot, 'app/sitemap.ts')
const googleVerificationPath = resolve(projectRoot, 'public/googlea3f2b8378fe5a305.html')

assert.ok(existsSync(resolve(projectRoot, 'assets/image/hero.jpg')), 'the local hero asset must exist')
assert.match(pageSource, /import heroImage from ['"]@\/assets\/image\/hero\.jpg['"]/, 'the page must import the local hero asset')
assert.match(pageSource, /<Image[^>]*src=\{heroImage\}[^>]*fill[^>]*className="[^"]*object-cover/, 'the hero must use the local image with full-bleed cover behavior')
assert.match(pageSource, /5531984761292/, 'all service calls must use the supplied WhatsApp number')
assert.match(pageSource, /20 anos de\s+experiência/, 'the hero must communicate experience')
assert.match(pageSource, /Prefira enviar\s+um\s+áudio/, 'the WhatsApp CTA must encourage audio messages')
assert.match(pageSource, /Atendimento\s+residencial e comercial/, 'the page must identify both service audiences')
assert.match(pageSource, /qualquer tipo de sinteco/, 'the services must cover every Sinteco finish')
assert.match(pageSource, /Cobrimos itens que não puderem ser movidos/, 'the FAQ must explain protection for immovable items')
assert.match(pageSource, /FaInstagram/, 'the floating Instagram action must use the official brand icon')
assert.match(pageSource, /FaWhatsapp/, 'the floating WhatsApp action must use the official brand icon')
assert.match(pageSource, /instagram\.com\/vanderli\.c\.scalafetador/, 'the floating Instagram action must link to the supplied profile')
assert.match(pageSource, /import dayjs from ['"]dayjs['"]/, 'the footer year must be derived with Day.js')
assert.match(pageSource, /dayjs\(\)\.year\(\)/, 'the footer year must update dynamically')
assert.match(pageSource, /Feito com/, 'the footer must include the requested authorship credit')
assert.match(pageSource, /linkedin\.com\/in\/efraimrsilva/, 'the authorship credit must link to the supplied LinkedIn profile')
assert.match(pageSource, /border-white\/10 px-5 pt-6 text-center text-sm text-white/, 'the updated footer credit must be white')
assert.match(pageSource, /transition-\[color,text-shadow\] duration-300/, 'the LinkedIn credit must animate color and text shadow for 0.3 seconds')
assert.match(pageSource, /hover:\[text-shadow:0_0_12px_rgb\(255_255_255_\/_0\.9\)\]/, 'the LinkedIn credit must gain a white shadow on hover')
assert.match(globalStyles, /html\s*\{[^}]*font-size:\s*17px/, 'the global type scale must increase by one pixel')
assert.match(pageSource, /text-\[11px\]/, 'the explicit ten-pixel label must also increase by one pixel')
assert.match(pageSource, /border-white\/10 px-5 pt-6 text-center text-sm text-white/, 'the final footer credit must be about two pixels larger')
assert.match(pageSource, /border-white\/10 px-5 pt-6 text-center text-sm text-white/, 'the final footer credit must be centered')
for (const videoId of ['DNtrF4q8Vhw', '-_sOfNAwLwA', '4tfvPW9etME']) {
  assert.match(pageSource, new RegExp(`videoId: ['"]${videoId}['"]`), `the gallery must include YouTube video ${videoId}`)
}
assert.match(pageSource, /youtube-nocookie\.com\/embed\/\$\{item\.videoId\}/, 'the gallery must use privacy-enhanced YouTube embeds')
assert.match(pageSource, /autoplay=1&mute=1&loop=1&playlist=\$\{item\.videoId\}&controls=0/, 'the gallery videos must autoplay silently in a loop without controls')
assert.match(pageSource, /rgba\(16,42,67,\.154\)_100%/, 'the right edge of the hero overlay must be 30 percent lighter')
assert.match(layoutSource, /import logo from ['"]@\/assets\/image\/logo\.png['"]/, 'the layout must use the supplied logo asset')
assert.match(layoutSource, /icons:\s*\{\s*icon:\s*logo\.src\s*\}/, 'the supplied logo must be registered as the page icon')

for (let index = 1; index <= 14; index += 1) {
  const extension = index <= 10 ? 'jpg' : 'png'
  assert.ok(existsSync(resolve(projectRoot, `assets/image/g${index}.${extension}`)), `gallery photo g${index} must exist`)
  assert.match(pageSource, new RegExp(`g${index}Image`), `gallery photo g${index} must be imported and used`)
}
assert.match(pageSource, /const \[activeGalleryImage, setActiveGalleryImage\] = useState\(0\)/, 'the photo gallery must track its active image')
assert.match(pageSource, /window\.setTimeout\([\s\S]*?6000/, 'the photo gallery must advance automatically every six seconds')
assert.match(pageSource, /aspect-\[10\/11\][\s\S]*?object-contain/, 'the main gallery image must use the updated average photo proportion without cropping')
assert.match(pageSource, /animate-in fade-in duration-500 ease-in-out transition-opacity/, 'the main gallery image must fade smoothly between photos')
assert.match(pageSource, /onClick=\{\(\) => setActiveGalleryImage\(index\)\}/, 'clicking a thumbnail must select its corresponding photo')
assert.match(pageSource, /sm:grid-cols-7[\s\S]*?lg:grid-cols-14/, 'the thumbnail strip must adapt from compact to wide screens')
assert.match(pageSource, /useRef/, 'the photo gallery must retain references to its thumbnails')
assert.doesNotMatch(pageSource, /scrollIntoView/, 'the gallery must not scroll the page vertically when a thumbnail changes')
assert.match(pageSource, /thumbnailRail\.scrollTo\(\{[\s\S]*?left:/, 'the gallery must scroll only its thumbnail rail horizontally')
assert.match(pageSource, /activeGalleryImage === 0\s*\? 0\s*:/, 'the thumbnail rail must return to its first item after the last photo')
assert.match(pageSource, /<header className="fixed inset-x-0 top-0 z-50/, 'the header must float above every section while the page scrolls')
assert.match(pageSource, /bg-primary\/95[^"]*backdrop-blur-sm/, 'the floating header must retain a readable translucent background')
assert.match(pageSource, /fixed bottom-24 right-5 z-50 flex items-center gap-3/, 'the floating social actions must clear the Netlify badge')
assert.match(pageSource, /id="por-que-escolher"/, 'the experience section must have a dedicated navigation anchor')
assert.match(pageSource, /"Por que nos escolher"/, 'the header navigation must include a compact value section label after the process')
assert.match(pageSource, /"#servicos"[\s\S]*?"#resultados"[\s\S]*?"#processo"[\s\S]*?"#por-que-escolher"[\s\S]*?"#faq"/, 'the header navigation must target the value section anchor')
assert.match(pageSource, /href="#processo"[\s\S]*?Processo/, 'the footer must link to the process section')
assert.match(pageSource, /href="#por-que-escolher"[\s\S]*?Por que nos escolher/, 'the footer must link to the value section')
assert.match(pageSource, /grid-rows-\[1fr\][\s\S]*?grid-rows-\[0fr\]|grid-rows-\[0fr\][\s\S]*?grid-rows-\[1fr\]/, 'FAQ answers must animate their height when opening and closing')
assert.match(pageSource, /opacity-100[\s\S]*?opacity-0|opacity-0[\s\S]*?opacity-100/, 'FAQ answers must fade smoothly during expansion')
assert.match(pageSource, /aria-expanded=\{openFaq === index\}/, 'FAQ controls must expose their expanded state to assistive technology')
assert.match(pageSource, /aria-hidden=\{openFaq !== index\}/, 'collapsed FAQ answers must be hidden from assistive technology')
assert.match(pageSource, /Raspagem e Aplicação de Sinteco WC/, 'the visible site identity must use the new brand')
assert.match(pageSource, /Restauração de Pisos de Madeira/, 'the visible site identity must state the service specialty')
assert.match(pageSource.replace(/\s+/g, " "), /Restauração de Pisos de Madeira\. Beleza, cuidado e acabamento que permanece\./, 'the footer must describe the official service specialty')
assert.match(pageSource, />\s*WC\s*<\/span>/, 'the header monogram must use the new brand initials')
assert.match(pageSource, /"Por que nos escolher"/, 'the compact navigation label must remain readable on small screens')
assert.doesNotMatch(pageSource, /Piso Nobre/, 'the visible page must not retain the previous brand')
assert.match(layoutSource, /Raspagem e Aplicação de Sinteco WC/, 'metadata must use the new brand')
assert.doesNotMatch(layoutSource, /Piso Nobre|piso nobre/, 'metadata must not retain the previous brand')
assert.match(readmeSource, /Raspagem e Aplicação de Sinteco WC/, 'the README must use the new brand')
assert.match(readmeSource, /https:\/\/github\.com\/efraimrsilva\/Sinteco-Portifolio\.git/, 'the README must use the renamed repository URL')
assert.doesNotMatch(readmeSource, /PisoNobre-Portifolio/, 'the README must not use the former repository name')
assert.ok(existsSync(robotsPath), 'the site must expose a robots.txt route')
assert.ok(existsSync(sitemapPath), 'the site must expose a sitemap.xml route')

const robotsSource = readFileSync(robotsPath, 'utf8')
const sitemapSource = readFileSync(sitemapPath, 'utf8')
const productionUrl = 'https://raspagemaplicacaosintecowc.netlify.app'

assert.match(layoutSource, /metadataBase/, 'metadata must define the production base URL')
assert.match(layoutSource, new RegExp(productionUrl), 'metadata must use the production domain')
assert.match(layoutSource, /alternates:\s*\{\s*canonical/, 'metadata must define a canonical URL')
assert.match(layoutSource, /openGraph:/, 'metadata must include Open Graph fields')
assert.match(layoutSource, /twitter:/, 'metadata must include Twitter card fields')
assert.match(pageSource, /application\/ld\+json/, 'the page must include structured data')
assert.match(pageSource, /ProfessionalService/, 'structured data must identify the local service business')
assert.match(pageSource, /areaServed/, 'structured data must specify the service area')
assert.match(robotsSource, /sitemap\.xml/, 'robots must advertise a sitemap URL')
assert.match(robotsSource, new RegExp(productionUrl), 'robots must use the production domain')
assert.match(sitemapSource, new RegExp(productionUrl), 'sitemap entries must use the production domain')
assert.ok(existsSync(googleVerificationPath), 'the Google Search Console verification file must be publicly available')
assert.equal(
  readFileSync(googleVerificationPath, 'utf8').trim(),
  'google-site-verification: googlea3f2b8378fe5a305.html',
  'the Google verification file must retain its exact supplied content',
)
assert.match(readmeSource, /https:\/\/raspagemaplicacaosintecowc\.netlify\.app/, 'the README must link to the published site')
assert.match(readmeSource, /## 🔎 SEO e indexação/, 'the README must document its SEO setup')
assert.match(readmeSource, /Google Search Console/, 'the README must document Google Search Console verification')
assert.match(readmeSource, /https:\/\/raspagemaplicacaosintecowc\.netlify\.app\/sitemap\.xml/, 'the README must document the sitemap submission URL')
